import 'package:day_night_time_picker/day_night_time_picker.dart';
import '../models/Task.dart';

List<Task> tasksData = [
  Task(
      title: 'Grocery Shopping',
      date: DateTime.now(),
      time: Time(hour: 10, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.shopping, Tag.urgent],
      des: 'Buy groceries for the week, including fruits, vegetables, and dairy products.'),
  Task(
      title: 'Team Meeting',
      date: DateTime(2024, 6, 13),
      time: Time(hour: 14, minute: 0),
      taskType: TaskType.work,
      tags: [Tag.office, Tag.important],
      des: 'Weekly team meeting to discuss project progress and upcoming deadlines.'),
  Task(
      title: 'Workout Session',
      date: DateTime.now(),
      time: Time(hour: 18, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.health, Tag.fitness],
      des: 'Attend evening workout session at the gym. Focus on strength training.'),
  Task(
      title: 'Project Deadline',
      date: DateTime.now(),
      time: Time(hour: 23, minute: 59),
      taskType: TaskType.work,
      tags: [Tag.urgent, Tag.office],
      des: 'Complete and submit the final project report before midnight.'),
  Task(
      title: 'Dentist Appointment',
      date: DateTime.now(),
      time: Time(hour: 9, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.health, Tag.important],
      des: 'Regular dental check-up and cleaning appointment.'),
  Task(
      title: 'Lunch with Friends',
      date: DateTime.now(),
      time: Time(hour: 12, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.social, Tag.important],
      des: 'Meet up with friends for lunch at the new restaurant downtown.'),
  Task(
      title: 'Code Review',
      date: DateTime.now(),
      time: Time(hour: 16, minute: 30),
      taskType: TaskType.work,
      tags: [Tag.office, Tag.urgent,Tag.hobby,Tag.health,Tag.social],
      des: 'Review code for the latest feature update before the end of the day.'),
  Task(
      title: 'Birthday Party',
      date: DateTime.now(),
      time: Time(hour: 19, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.social, Tag.fun],
      des: 'Attend a friend’s birthday party. Bring a gift and have fun.'),
  Task(
      title: 'Submit Report',
      date: DateTime.now(),
      time: Time(hour: 17, minute: 0),
      taskType: TaskType.work,
      tags: [Tag.office],
      des: 'Submit the weekly report to the manager before the end of the day.'),
  Task(
      title: 'Yoga Class',
      date: DateTime.now(),
      time: Time(hour: 6, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.health, Tag.social],
      des: 'Attend the morning yoga class to start the day with relaxation and mindfulness.'),
  Task(
      title: 'Client Call',
      date: DateTime.now(),
      time: Time(hour: 11, minute: 0),
      taskType: TaskType.work,
      tags: [Tag.office, Tag.important],
      des: 'Conference call with the client to discuss project requirements and updates.'),
  Task(
      title: 'Read Book',
      date: DateTime.now(),
      time: Time(hour: 20, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.hobby, Tag.relaxation],
      des: 'Spend an hour reading a new book before bed.'),
  Task(
      title: 'Doctor Appointment',
      date: DateTime.now(),
      time: Time(hour: 15, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.health, Tag.important],
      des: 'Visit the doctor for a routine health check-up.'),
  Task(
      title: 'Finish Presentation',
      date: DateTime.now(),
      time: Time(hour: 13, minute: 30),
      taskType: TaskType.work,
      tags: [Tag.office, Tag.urgent],
      des: 'Complete the presentation for the upcoming meeting.'),
  Task(
      title: 'Family Dinner',
      date: DateTime.now(),
      time: Time(hour: 19, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.social, Tag.important],
      des: 'Have dinner with family at home.'),
  Task(
      title: 'Buy Birthday Gift',
      date: DateTime.now(),
      time: Time(hour: 17, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.shopping, Tag.urgent],
      des: 'Purchase a gift for a friend’s upcoming birthday party.'),
  Task(
      title: 'Write Blog Post',
      date: DateTime.now(),
      time: Time(hour: 10, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.creative, Tag.important],
      des: 'Write and publish a new blog post on personal development.'),
  Task(
      title: 'Gardening',
      date: DateTime.now(),
      time: Time(hour: 8, minute: 0),
      taskType: TaskType.personal,
      tags: [Tag.hobby, Tag.relaxation],
      des: 'Spend the morning working on the garden, planting new flowers.'),
  Task(
      title: 'Plan Vacation',
      date: DateTime.now(),
      time: Time(hour: 14, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.planning, Tag.fun],
      des: 'Plan the itinerary for the upcoming vacation.'),
  Task(
      title: 'Car Maintenance',
      date: DateTime.now(),
      time: Time(hour: 9, minute: 30),
      taskType: TaskType.personal,
      tags: [Tag.important, Tag.urgent],
      des: 'Take the car for its scheduled maintenance and check-up.'),
  Task(
      title: 'Brainstorming Session',
      date: DateTime.now(),
      time: Time(hour: 11, minute: 30),
      taskType: TaskType.work,
      tags: [Tag.office, Tag.creative, Tag.urgent,Tag.hobby,Tag.health],
      des: 'Team brainstorming session to generate new ideas for the project.'),
];
